version: '3'

services:
  nestapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nest-docker 
    container_name: backend-nest
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/nest-app
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_KEY: ${JWT_KEY}
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres-nest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
